# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'UseNetwork' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'AFNetworking', '~> 2.6'
  pod 'SDWebImage', '~>3.8'

  # Pods for UseNetwork

  target 'UseNetworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
