# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'NetworkProject' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NetworkProject

pod 'AFNetworking', '~> 3.1.0'
pod 'SBJson', '~> 4.0.1'
pod 'SDWebImage', '~>3.8'

  target 'NetworkProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NetworkProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
